# Generated by Django 5.1.6 on 2025-02-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_customer_delete_activeclient_delete_officialaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
