# Generated by Django 5.1.6 on 2025-02-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='client_id',
        ),
    ]
