# Generated by Django 5.1.6 on 2025-02-28 17:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_customer_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional name or description for the area', max_length=100, null=True)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(help_text='Geographic area for which saturation is measured', srid=4326)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Center of the area, for marker display', null=True, srid=4326)),
                ('active_clients', models.PositiveIntegerField(default=0, help_text='Number of active clients in the area')),
                ('inactive_clients', models.PositiveIntegerField(default=0, help_text='Number of inactive clients in the area')),
                ('computed_at', models.DateTimeField(auto_now=True, help_text='The time when these measures were computed')),
            ],
        ),
    ]
