# Generated by Django 5.1.6 on 2025-03-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street_no',
            field=models.CharField(max_length=50),
        ),
    ]
